services:
  nextjs:
    environment:
      COREPACK_ENABLE_DOWNLOAD_PROMPT: 0
      GIT_USER_NAME: ${GIT_USER_NAME}
      GIT_USER_EMAIL: ${GIT_USER_EMAIL}
      GITHUB_REPOS: ${GITHUB_REPOS}
      GITHUB_OWNER: ${GITHUB_OWNER}
      GITHUB_BLOG_PATH: ${GITHUB_BLOG_PATH}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL}
      NEXT_PUBLIC_GA4_MEASUREMENT_ID: ${NEXT_PUBLIC_GA4_MEASUREMENT_ID}
      NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION: ${NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION}
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    working_dir: /workspace
    volumes:
      - ..:/workspace:cached
    ports:
      - "3000:3000"
    stop_signal: SIGINT
    stdin_open: true
    tty: true
